### ISSUE TITLE
Решить какую авторизацию подключить

### ISSUE THREAD

**Issue by runtime05** [runtime05/SafeRealTimeChat#2]
Нужно принять решение какую авторизацию подключить:
https://proglib.io/p/veb-autentifikaciya-fayly-cookies-ili-tokeny-2021-08-14#:~:text=Cookie%2DBased%20Authentication,%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0%20%D0%B8%20%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%D1%81%D1%8F%20%D0%B2%20%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80. - почитать и отписать свое решение здесь.

**Comment by runtime05** [comment]
Выбор стоит между Jwt токенами и Cookies

**Comment by runtime05** [comment]
так же подумать нужна ли вообще нам авторизация, учитывая суть проекта

**Comment by Timaf9n** [comment]
Я склоняюсь к cookie,из-за лучшей защищённости .Но в cookie есть ограничение памяти.

**Comment by Timaf9n** [comment]
Это его уязвимость к xss атакам.Я так понял что cookie тоже может быть атакован xss,но прочитать токен не получится

**Comment by runtime05** [comment]
Сошлись на том, что в рамках текущего проекта авторизация вовсе не нужна.
